INCLUDES = -I..

all:
	$(CC) $(INCLUDES) create.c -o create.out
	$(CC) $(INCLUDES) parse_and_print.c -o parse_and_print.out
	$(CC) $(INCLUDES) parse_string.c -o parse_string.out

clean:
	rm create.out parse_and_print.out parse_string.out